method: grid
metric: 
  goal: maximize
  name: val/loss_mean
parameters:
  acc_factor_data:
    values: [2, 4, 10, 20, 40, 100]
  loss_name:
    values: ['psnr', 'ssim']
program: scripts/16-TrainingSamplesSweep.py